import type { Request, Response, NextFunction } from "express";
import { User } from "../models/User.ts";
import { PLAN_CONFIGS, type PlanConfig } from "../config/plan.config.ts";

// Helper: Resets monthly counters if 30 days have elapsed since last reset
const checkAndResetMonthlyQuota = async (user: any) => {
  const now = new Date();
  const lastReset = user.monthlyUsage?.lastResetDate
    ? new Date(user.monthlyUsage.lastResetDate)
    : now;

  const diffDays = (now.getTime() - lastReset.getTime()) / (1000 * 3600 * 24);

  if (diffDays >= 30) {
    user.monthlyUsage = {
      manualGenerationsCount: 0,
      autoGenerationsCount: 0,
      lastResetDate: now,
    };
    await user.save();
  }
};

export const enforcePlanLimits = (isAutoGenerated = false) => {
  return async (req: Request, res: Response, next: NextFunction) => {
    try {
      // Assumes user ID attached by your authentication middleware (e.g., req.id or req.user._id)
      const userId = (req as any).id || (req as any).user?._id;

      if (!userId) {
        return res
          .status(401)
          .json({ success: false, message: "Unauthorized access!" });
      }

      const user = await User.findById(userId);
      if (!user) {
        return res
          .status(404)
          .json({ success: false, message: "User not found!" });
      }

      // 1. Check if paid subscription has expired
      if (
        user.plan !== "FREE" &&
        user.premiumExpiresAt &&
        new Date() > new Date(user.premiumExpiresAt)
      ) {
        user.plan = "FREE";
        user.premiumExpiresAt = null;
        await user.save();
      }

      // 2. Ensure monthly usage counters are initialized and reset if needed
      if (!user.monthlyUsage) {
        user.monthlyUsage = {
          videosGenerated: 0,
          manualGenerationsCount: 0,
          autoGenerationsCount: 0,
          lastResetDate: new Date(),
        };
        await user.save();
      }

      await checkAndResetMonthlyQuota(user);

      const planConfig: PlanConfig = PLAN_CONFIGS[user.plan || "FREE"];

      // 3. Verify Quotas based on mode (Automated vs Manual)
      if (isAutoGenerated) {
        if (planConfig.autoPostLimit === 0) {
          return res.status(403).json({
            success: false,
            message:
              "Automated generation and posting are not available on the Free plan. Upgrade to Pro or Ultimate.",
          });
        }

        if (
          planConfig.autoPostLimit !== -1 &&
          user.monthlyUsage.autoGenerationsCount >= planConfig.autoPostLimit
        ) {
          return res.status(429).json({
            success: false,
            message: `Monthly auto-generation limit reached (${planConfig.autoPostLimit}/${planConfig.autoPostLimit}). Upgrade your plan for additional posts.`,
          });
        }
      } else {
        if (
          planConfig.manualLimit !== -1 &&
          user.monthlyUsage.manualGenerationsCount >= planConfig.manualLimit
        ) {
          return res.status(429).json({
            success: false,
            message: `Monthly manual video generation limit reached (${planConfig.manualLimit}/${planConfig.manualLimit}). Please upgrade your plan.`,
          });
        }
      }

      // Attach user document and resolved plan config to request for use in controllers
      (req as any).userInstance = user;
      (req as any).planConfig = planConfig;

      next();
    } catch (error: any) {
      return res.status(500).json({
        success: false,
        message: error.message || "Failed to verify subscription plan limits.",
      });
    }
  };
};
